// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDest9kDoLiUpYPFunKFP3bhk3vuZslhAU',
    appId: '1:92387396428:web:d45b19b4747c96b1745de9',
    messagingSenderId: '92387396428',
    projectId: 'irequest-f48cd',
    authDomain: 'irequest-f48cd.firebaseapp.com',
    storageBucket: 'irequest-f48cd.appspot.com',
    measurementId: 'G-4G0PLJJG9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWySWkrWAk8u4cs9V1kLE465wJKRp_0w',
    appId: '1:92387396428:android:dcc4ef1c64a74d76745de9',
    messagingSenderId: '92387396428',
    projectId: 'irequest-f48cd',
    storageBucket: 'irequest-f48cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2oayL2wwd6S-8qjQG0D8Awwo09YHjnOY',
    appId: '1:92387396428:ios:3a256821af3bd5f1745de9',
    messagingSenderId: '92387396428',
    projectId: 'irequest-f48cd',
    storageBucket: 'irequest-f48cd.appspot.com',
    iosClientId: '92387396428-f1b4uvdnk509prud46rkkbmd9j9lg11b.apps.googleusercontent.com',
    iosBundleId: 'site.irequest.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2oayL2wwd6S-8qjQG0D8Awwo09YHjnOY',
    appId: '1:92387396428:ios:3a256821af3bd5f1745de9',
    messagingSenderId: '92387396428',
    projectId: 'irequest-f48cd',
    storageBucket: 'irequest-f48cd.appspot.com',
    iosClientId: '92387396428-f1b4uvdnk509prud46rkkbmd9j9lg11b.apps.googleusercontent.com',
    iosBundleId: 'site.irequest.mobile',
  );
}
